### ISSUE TITLE
Error loading data...

### ISSUE THREAD

**Issue by weisisheng** [weaviate/healthsearch-demo#6]
Trying to load the sample from this demo, connection is made, data is read/loaded and product class is created.

However the following error surfaces:

  File "/home/ubuntu/weaviate-apps/healthcare-demo/import_data_to_weaviate.py", line 175, in main
    "name": data[d].get("name", "Productname"),

Data is a json object.  Do I have to convert this to a dictionary before importing?  Not super facile with Python (10.x) and grubbing around google didn't raise anything.

TIA

---

Addendum: Oddly, the data wouldn't load from / on a remote docker instance but I was able to send the data from a local machine to the remote instance.

**Comment by thomashacker** [comment]
Interesting! Could you explain which approach you used to set up the demo? I think the issue could've been that dockerized applications have their own network, so access from outside the container might not work as expected.

**Comment by weisisheng** [comment]
Let me work thru it again in the next 2-3 days and return with comments.

**Comment by thomashacker** [comment]
Issue resolved here https://github.com/weaviate/healthsearch-demo/issues/10
