### ISSUE TITLE
Error in backend README & script for dataloader

### ISSUE THREAD

**Issue by corticalstack** [weaviate/healthsearch-demo#7]
Hi,

Error in backend-specific README.md, refers to example supplements dataset loader as being in sub-folder scripts, which does not exist, the .py script is in the backend folder.

Script `import_data_to_weaviate.py` also incorrectly names the environment variables for Weaviate cluster and key incorrectly (not same as proposed keys in backend README setup).

Thanks

**Comment by thomashacker** [comment]
Nice catch! Thanks a lot.

Fixed in this PR https://github.com/weaviate/healthsearch-demo/pull/8
